name: Build Android Debug APK

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Set Up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Packages
        run: |
          sdkmanager \
          "platform-tools" \
          "platforms;android-34" \
          "build-tools;34.0.0"

      - name: Reconstruct keystore
        run: |
          echo "$KEYSTORE_B64" | base64 --decode > regenwall.keystore
        env:
          KEYSTORE_B64: ${{ secrets.KEYSTORE_B64 }}


      - name: Cache Gradle Packages (hopefully)
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles("**/*.gradle*", "**/gradle-wrapper.properties")
        if: always()

      
      - name: Lint Everything But Java
        run: ./gradlew lintDebug -x compileDebugJavaWithJavac compileDebugKotlin
        env:
          GRADLE_OPTS: >
            -Dorg.gradle.internal.http.connectionTimeout=60000
            -Dorg.gradle.internal.http.socketTimeout=60000
            -Dorg.gradle.internal.repository.max.retries=5
            -Dorg.gradle.internal.repository.initial.backoff=2000

      - name: Lint (Java Kaught Lint Edition)
        run: ./gradlew lintDebug --continue
        continue-on-error: true

      - name: Find Lint Reports
        run: |
          echo "==== build/reports ===="
          find app/build/reports/lint -type f || true

      - name: Upload Lint Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lint-report
          path: app/build/reports/lint/

      - name: Enforce Lint Results
        run: ./gradlew lint

      - name: Build debug APK
        run: ./gradlew assembleDebug
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: regenwall-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
