name: Debug Building Process

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Set Up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Packages
        run: |
          sdkmanager \
          "platform-tools" \
          "platforms;android-34" \
          "build-tools;34.0.0"

      - name: Verify SDK install
        run: |
          echo "ANDROID_HOME: $ANDROID_HOME"
          ls $ANDROID_HOME/platforms
          ls $ANDROID_HOME/platforms/android-34/android.jar

      - name: Debug dependencies list
        run: |
          ./gradlew :app:dependencies --configuration debugRuntimeClasspath

      - name: Verify Gradle Tasks
        run: |
          ./gradlew :app:tasks | grep compile
